--Haskell functions can be grouped into modules.
--A Haskell module is somewhere between a class and a package in Java
--There are many built in modules
--Modules are things like Data.List, Data.Char, Data.Map, Data.Set
--When we log into ghci, the Prelude module is what shows up by default